### ISSUE TITLE
3.6.3  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by stevenwsg** [bmob/bmob-android-sdk#29]
你好，我用3.6.3获取数据的时候，没开线程，在主线程中获取数据报这个错误，以下是详细信息
FATAL EXCEPTION: RxIoScheduler-18
                                                                Process: com.wsg.xsybbs, PID: 11055
                                                                java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                 Caused by: java.lang.OutOfMemoryError
                                                                    at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
                                                                    at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:124)
                                                                    at java.lang.StringBuilder.append(StringBuilder.java:271)
                                                                    at java.io.BufferedReader.readLine(BufferedReader.java:414)
                                                                    at cn.bmob.v3.datatype.a.This.I(AsyncRun.java:6104)
                                                                    at cn.bmob.v3.http.b.of.Code(ResponseInterceptor.java:34)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.a.b.This.Code(ConnectInterceptor.java:46)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:1068)
                                                                    at cn.bmob.v3.b.a.a.This.Code(CacheInterceptor.java:94)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:1068)
                                                                    at cn.bmob.v3.b.a.c.This.Code(BridgeInterceptor.java:94)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.a.c.mine.Code(RetryAndFollowUpInterceptor.java:122)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:1068)
                                                                    at cn.bmob.v3.http.b.This.Code(GzipRequestInterceptor.java:23)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:1068)
                                                                    at cn.bmob.v3.http.b.thing.Code(HttpLoggingInterceptor.java:129)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:3093)
                                                                    at cn.bmob.v3.b.method$This.Code(Interceptor.java:1068)
                                                                    at cn.bmob.v3.b.ii.V(RealCall.java:180)
                                                                    at cn.bmob.v3.b.ii.Code(RealCall.java:64)
                                                                    at cn.bmob.v3.http.This$4.call(BmobClient.java:1441)
                                                                    at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)?
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)?
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)?
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)?
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)?
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)?
                                                                    at java.lang.Thread.run(Thread.java:841)

我是一名大三学生，这几天在学校实习，项目一直在赶，可是这个bug解决不了
忘尽快回复

**Comment by stevenwsg** [comment]
你好 ，不好意思，打扰了~~~~~
是我的逻辑写的有问题，已经解决了
非常感谢
