### ISSUE TITLE
小米6，MIUI10.0，APK自动更新，点击更新按钮后闪退。

### ISSUE THREAD

**Issue by yknn** [bmob/bmob-android-sdk#35]
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at cn.bmob.v3.util.InstallUtil.startInstall(InstallUtil.java:49)
        at cn.bmob.v3.update.BmobUpdateAgent.Code(BmobUpdateAgent.java:1248)
        at cn.bmob.v3.update.UpdateDialogActivity.onDestroy(UpdateDialogActivity.java:140)
        at android.app.Activity.performDestroy(Activity.java:7252)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4490)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4521)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/base.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_resources_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/lib/arm64, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/base.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2019-01-02 00:01:46.004 16388-16388/com.test.yukun.testbomb2 E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 15 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.test.yukun.testbomb2-kRMH_T97wjIoEpYflDgi8A==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5757)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        		... 6 more`

**Comment by juemuren4449** [comment]
@yknn 
bmob sdk 中的 InstallUtil 类使用了 AndroidX 的包，只需要将你的项目依赖升级为 AndroidX 即可。
具体操作：
1. 点击 Refactor
2. 选择 Migrate to AndroidX
studio 将自动替换对应的包名，如果有未替换的，手动替换即可。
